default:
  model:
    model_name: distilbert-base-uncased
    num_node_features: 300
    nout: 32
    nhid: 512
    graph_hidden_channels: 512
  optim:
    optimizer: AdamW
    scheduler: cosine
    batch_size: 32
    eval_batch_size: 32
    lr_initial: 5e-5
    lr_min: 5e-6
    warmup_steps: 1
    weight_decay: 0.01
    loss: contrastive
    max_epochs: 20

scibert:
  model:
    model_name: allenai/scibert_scivocab_uncased
  optim:
    lr_initial: 2e-5
    max_epochs: 10