default:
  model:
    model_name: distilbert-base-uncased
    num_node_features: 300
    nout: 32
    nhid: 512
    num_query_token: 8
    nlayers: 3
    graph_hidden_channels: 512
  optim:
    optimizer: AdamW
    scheduler: cosine
    batch_size: 128
    eval_batch_size: 16
    # warmup_factor: 0.05
    lr_initial: 5e-5
    lr_min: 5e-6
    warmup_steps: 1
    # lr_decay_rate: 0.9
    # weight_decay: 0.05
    loss: contrastive
    max_epochs: 25
    # lr_gamma: 0.9

defaultgat:
  model:
    model_name: distilbert-base-uncased
    graph_encoder_type: gat
  optim:
    max_epochs: 50

scibert:
  model:
    model_name: allenai/scibert_scivocab_uncased
  optim:
    max_epochs: 10
  
scibertgat:
  model:
    model_name: allenai/scibert_scivocab_uncased
    graph_encoder_type: gat
  optim:
    max_epochs: 10